-- Run this file once in Supabase: SQL Editor -> New query -> Run.
-- It does not delete or replace existing application data.

BEGIN;

-- Columns used by the Streamlit application.
ALTER TABLE IF EXISTS public.events ADD COLUMN IF NOT EXISTS is_archived boolean DEFAULT false;
ALTER TABLE IF EXISTS public.events ADD COLUMN IF NOT EXISTS event_image_path text;
ALTER TABLE IF EXISTS public.events ADD COLUMN IF NOT EXISTS last_updated timestamptz DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS public.locations ADD COLUMN IF NOT EXISTS is_archived boolean DEFAULT false;
ALTER TABLE IF EXISTS public.locations ADD COLUMN IF NOT EXISTS last_updated timestamptz DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS public.event_types ADD COLUMN IF NOT EXISTS is_archived boolean DEFAULT false;
ALTER TABLE IF EXISTS public.event_types ADD COLUMN IF NOT EXISTS last_updated timestamptz DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS public.participants ADD COLUMN IF NOT EXISTS is_archived boolean DEFAULT false;
ALTER TABLE IF EXISTS public.participants ADD COLUMN IF NOT EXISTS blocked_flag boolean DEFAULT false;
ALTER TABLE IF EXISTS public.participants ADD COLUMN IF NOT EXISTS last_updated timestamptz DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS public.partners ADD COLUMN IF NOT EXISTS is_archived boolean DEFAULT false;
ALTER TABLE IF EXISTS public.partners ADD COLUMN IF NOT EXISTS last_updated timestamptz DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS public.event_registration ADD COLUMN IF NOT EXISTS last_updated timestamptz DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE IF EXISTS public.event_registered_attendee ADD COLUMN IF NOT EXISTS last_updated timestamptz DEFAULT CURRENT_TIMESTAMP;

-- Convert SQLite-style 0/1 archive columns to PostgreSQL booleans when needed.
DO $migration$
DECLARE
    table_item text;
    column_type text;
BEGIN
    FOREACH table_item IN ARRAY ARRAY['events', 'locations', 'event_types', 'participants', 'partners']
    LOOP
        SELECT data_type
        INTO column_type
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = table_item
          AND column_name = 'is_archived';

        IF column_type IS NOT NULL AND column_type <> 'boolean' THEN
            EXECUTE format(
                'ALTER TABLE public.%I ALTER COLUMN is_archived DROP DEFAULT',
                table_item
            );
            EXECUTE format(
                'ALTER TABLE public.%I ALTER COLUMN is_archived TYPE boolean '
                'USING CASE WHEN is_archived IS NULL THEN false '
                'WHEN lower(is_archived::text) IN (''1'', ''true'', ''t'', ''yes'', ''y'') '
                'THEN true ELSE false END',
                table_item
            );
            EXECUTE format(
                'ALTER TABLE public.%I ALTER COLUMN is_archived SET DEFAULT false',
                table_item
            );
        END IF;
    END LOOP;
END
$migration$;

UPDATE public.events SET is_archived = false WHERE is_archived IS NULL;
UPDATE public.locations SET is_archived = false WHERE is_archived IS NULL;
UPDATE public.event_types SET is_archived = false WHERE is_archived IS NULL;
UPDATE public.participants SET is_archived = false WHERE is_archived IS NULL;
UPDATE public.participants SET blocked_flag = false WHERE blocked_flag IS NULL;
UPDATE public.partners SET is_archived = false WHERE is_archived IS NULL;

-- PostgreSQL audit table. JSONB lets the app inspect and undo changes safely.
CREATE TABLE IF NOT EXISTS public.audit_log (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    table_name text NOT NULL,
    record_id text,
    action text NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    operator text,
    source text NOT NULL DEFAULT 'postgres_trigger',
    before_json jsonb,
    after_json jsonb,
    undone boolean NOT NULL DEFAULT false,
    undo_audit_id bigint,
    transaction_id bigint NOT NULL DEFAULT txid_current()
);

ALTER TABLE public.audit_log ADD COLUMN IF NOT EXISTS undone boolean DEFAULT false;
ALTER TABLE public.audit_log ADD COLUMN IF NOT EXISTS undo_audit_id bigint;
ALTER TABLE public.audit_log ADD COLUMN IF NOT EXISTS transaction_id bigint DEFAULT txid_current();

-- Make an audit table imported from SQLite compatible with PostgreSQL.
DO $audit_migration$
DECLARE
    audit_id_is_identity text;
    audit_column_type text;
BEGIN
    SELECT is_identity
    INTO audit_id_is_identity
    FROM information_schema.columns
    WHERE table_schema='public' AND table_name='audit_log' AND column_name='audit_id';

    IF audit_id_is_identity = 'NO' THEN
        CREATE SEQUENCE IF NOT EXISTS public.audit_log_audit_id_seq;
        PERFORM setval(
            'public.audit_log_audit_id_seq',
            COALESCE((SELECT MAX(audit_id) FROM public.audit_log), 0) + 1,
            false
        );
        ALTER TABLE public.audit_log
            ALTER COLUMN audit_id SET DEFAULT nextval('public.audit_log_audit_id_seq');
    END IF;

    SELECT data_type INTO audit_column_type
    FROM information_schema.columns
    WHERE table_schema='public' AND table_name='audit_log' AND column_name='undone';
    IF audit_column_type IS NOT NULL AND audit_column_type <> 'boolean' THEN
        ALTER TABLE public.audit_log ALTER COLUMN undone DROP DEFAULT;
        ALTER TABLE public.audit_log ALTER COLUMN undone TYPE boolean
        USING CASE WHEN undone IS NULL THEN false
                   WHEN lower(undone::text) IN ('1', 'true', 't', 'yes', 'y') THEN true
                   ELSE false END;
        ALTER TABLE public.audit_log ALTER COLUMN undone SET DEFAULT false;
    END IF;

    SELECT data_type INTO audit_column_type
    FROM information_schema.columns
    WHERE table_schema='public' AND table_name='audit_log' AND column_name='before_json';
    IF audit_column_type IS NOT NULL AND audit_column_type <> 'jsonb' THEN
        ALTER TABLE public.audit_log ALTER COLUMN before_json TYPE jsonb
        USING NULLIF(before_json::text, '')::jsonb;
    END IF;

    SELECT data_type INTO audit_column_type
    FROM information_schema.columns
    WHERE table_schema='public' AND table_name='audit_log' AND column_name='after_json';
    IF audit_column_type IS NOT NULL AND audit_column_type <> 'jsonb' THEN
        ALTER TABLE public.audit_log ALTER COLUMN after_json TYPE jsonb
        USING NULLIF(after_json::text, '')::jsonb;
    END IF;
END
$audit_migration$;

UPDATE public.audit_log SET undone=false WHERE undone IS NULL;
UPDATE public.audit_log SET transaction_id=txid_current() WHERE transaction_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_audit_log_table_record
    ON public.audit_log (table_name, record_id, changed_at DESC);

-- Apply last_updated consistently, including edits made outside Streamlit.
CREATE OR REPLACE FUNCTION public.ssc_set_last_updated()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.last_updated := CURRENT_TIMESTAMP;
    RETURN NEW;
END
$function$;

-- One generic audit function; primary-key column names are trigger arguments.
CREATE OR REPLACE FUNCTION public.ssc_capture_audit()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
    before_data jsonb;
    after_data jsonb;
    record_data jsonb;
    audit_record_id text;
    operator_name text;
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        before_data := to_jsonb(OLD);
    END IF;
    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        after_data := to_jsonb(NEW);
    END IF;

    record_data := CASE WHEN TG_OP = 'DELETE' THEN before_data ELSE after_data END;

    SELECT string_agg(record_data ->> key_name, '/' ORDER BY ordinal_position)
    INTO audit_record_id
    FROM unnest(TG_ARGV) WITH ORDINALITY AS keys(key_name, ordinal_position);

    operator_name := COALESCE(
        NULLIF(current_setting('app.operator', true), ''),
        'SSC Admin'
    );

    INSERT INTO public.audit_log (
        table_name,
        record_id,
        action,
        operator,
        source,
        before_json,
        after_json,
        transaction_id
    ) VALUES (
        TG_TABLE_NAME,
        audit_record_id,
        TG_OP,
        operator_name,
        'postgres_trigger',
        before_data,
        after_data,
        txid_current()
    );

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END
$function$;

-- Recreate application triggers idempotently.
DROP TRIGGER IF EXISTS ssc_last_updated ON public.events;
CREATE TRIGGER ssc_last_updated BEFORE UPDATE ON public.events
FOR EACH ROW EXECUTE FUNCTION public.ssc_set_last_updated();
DROP TRIGGER IF EXISTS ssc_audit_changes ON public.events;
CREATE TRIGGER ssc_audit_changes AFTER INSERT OR UPDATE OR DELETE ON public.events
FOR EACH ROW EXECUTE FUNCTION public.ssc_capture_audit('event_id');

DROP TRIGGER IF EXISTS ssc_last_updated ON public.locations;
CREATE TRIGGER ssc_last_updated BEFORE UPDATE ON public.locations
FOR EACH ROW EXECUTE FUNCTION public.ssc_set_last_updated();
DROP TRIGGER IF EXISTS ssc_audit_changes ON public.locations;
CREATE TRIGGER ssc_audit_changes AFTER INSERT OR UPDATE OR DELETE ON public.locations
FOR EACH ROW EXECUTE FUNCTION public.ssc_capture_audit('location_id');

DROP TRIGGER IF EXISTS ssc_last_updated ON public.event_types;
CREATE TRIGGER ssc_last_updated BEFORE UPDATE ON public.event_types
FOR EACH ROW EXECUTE FUNCTION public.ssc_set_last_updated();
DROP TRIGGER IF EXISTS ssc_audit_changes ON public.event_types;
CREATE TRIGGER ssc_audit_changes AFTER INSERT OR UPDATE OR DELETE ON public.event_types
FOR EACH ROW EXECUTE FUNCTION public.ssc_capture_audit('etype_id');

DROP TRIGGER IF EXISTS ssc_last_updated ON public.participants;
CREATE TRIGGER ssc_last_updated BEFORE UPDATE ON public.participants
FOR EACH ROW EXECUTE FUNCTION public.ssc_set_last_updated();
DROP TRIGGER IF EXISTS ssc_audit_changes ON public.participants;
CREATE TRIGGER ssc_audit_changes AFTER INSERT OR UPDATE OR DELETE ON public.participants
FOR EACH ROW EXECUTE FUNCTION public.ssc_capture_audit('participant_id');

DROP TRIGGER IF EXISTS ssc_last_updated ON public.partners;
CREATE TRIGGER ssc_last_updated BEFORE UPDATE ON public.partners
FOR EACH ROW EXECUTE FUNCTION public.ssc_set_last_updated();
DROP TRIGGER IF EXISTS ssc_audit_changes ON public.partners;
CREATE TRIGGER ssc_audit_changes AFTER INSERT OR UPDATE OR DELETE ON public.partners
FOR EACH ROW EXECUTE FUNCTION public.ssc_capture_audit('partner_id');

DROP TRIGGER IF EXISTS ssc_last_updated ON public.event_registration;
CREATE TRIGGER ssc_last_updated BEFORE UPDATE ON public.event_registration
FOR EACH ROW EXECUTE FUNCTION public.ssc_set_last_updated();
DROP TRIGGER IF EXISTS ssc_audit_changes ON public.event_registration;
CREATE TRIGGER ssc_audit_changes AFTER INSERT OR UPDATE OR DELETE ON public.event_registration
FOR EACH ROW EXECUTE FUNCTION public.ssc_capture_audit('registration_id');

DROP TRIGGER IF EXISTS ssc_last_updated ON public.event_registered_attendee;
CREATE TRIGGER ssc_last_updated BEFORE UPDATE ON public.event_registered_attendee
FOR EACH ROW EXECUTE FUNCTION public.ssc_set_last_updated();
DROP TRIGGER IF EXISTS ssc_audit_changes ON public.event_registered_attendee;
CREATE TRIGGER ssc_audit_changes AFTER INSERT OR UPDATE OR DELETE ON public.event_registered_attendee
FOR EACH ROW EXECUTE FUNCTION public.ssc_capture_audit('registration_id', 'participant_id');

COMMIT;
